#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

COMPAT_SCRIPT=".scripts/editor_compat"
if [[ -f "$COMPAT_SCRIPT" ]];then
    source "$COMPAT_SCRIPT"
fi
if [[ -z "$BRAINDUMP_EDITOR" ]]; then
    BRAINDUMP_EDITOR="nano"
    function bd_open_file_line () { cat "/dev/null"; }
fi
export BRAINDUMP_EDITOR

if [[ -z "$BRAINDUMP_FILE_SUFFIX" ]]; then
    BRAINDUMP_FILE_SUFFIX=".txt"
fi

mkdir -p ideas
CONTEXT_DESC=""
if [[ -x ".getdesc" ]]; then
    CONTEXT_DESC="_""`./.getdesc`"
elif [[ -f ".getdesc" ]]; then
    echo "Error: .getdesc exists but is not executable"
    exit 1
fi
DATE_DESC="_$(date +%Y-%m-%d)"
IDEAFILE="ideas/idea${CONTEXT_DESC}${DATE_DESC}${BRAINDUMP_FILE_SUFFIX}";


if [[ "$1" == "?" && -z "$2" ]]; then
    echo "$IDEAFILE"
elif [ -n "$1" ]; then
    echo "$1" >> "$IDEAFILE"
    echo "Added idea: \"$(tail -n 1 "$IDEAFILE")\""
else
    if [[ "$BRAINDUMP_EDITOR" =~ vim ]]; then
        $BRAINDUMP_EDITOR + "$IDEAFILE"
    elif [[ "$BRAINDUMP_EDITOR_OPEN_WITH" == true ]]; then
        if [[ -f "$IDEAFILE" ]]; then
            LAST_LINE="`grep -c "" "$IDEAFILE" `"
        fi
        bd_open_file_line "$IDEAFILE" "$LAST_LINE"
    else
        $BRAINDUMP_EDITOR "$IDEAFILE"
    fi
fi
