#!/bin/bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

mkdir -p logs;

LOGNAME="$1"
if [[ -z "$1" || "$1" == "?" ]]; then
    LOGNAME="log"
fi
if [[ "$1" != "?" ]]; then
    shift
fi
QM="$1"

CDIR="$(pwd)"
mkdir -p logs
cd logs
MATCHING="$(printf "$(find . | grep -is $LOGNAME)")"
cd "$CDIR"

if [ -z "$MATCHING" ]; then
    LOGFILE="logs/${LOGNAME}_$(date +%Y-%m-%d).txt"
else
    LOGFILE="logs/${MATCHING[0]}"
fi;

if [[ "$QM" == "?" ]]; then
    echo "$LOGFILE"
else
    vim "$LOGFILE" -s .scripts/vim_log_start
fi
