#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

COMPAT_SCRIPT=".scripts/editor_compat"
if [[ -f "$COMPAT_SCRIPT" ]];then
    source "$COMPAT_SCRIPT"
fi
if [[ -z "$BRAINDUMP_EDITOR" ]]; then
    BRAINDUMP_EDITOR="nano -T 4 -Eli --softwrap"
fi
export BRAINDUMP_EDITOR

mkdir -p notes
CONTEXT_DESC=""
if [[ -x ".getdesc" ]]; then
    CONTEXT_DESC="_""`./.getdesc`"
elif [[ -f ".getdesc" ]]; then
    echo "Error: .getdesc exists but is not executable"
    exit 1
fi
DATE_DESC="_$(date +%Y-%m-%d)"
NOTEFILE="notes/note${CONTEXT_DESC}${DATE_DESC}.txt";


if [[ "$1" == "?" && -z "$2" ]]; then
    echo "$NOTEFILE"
elif [ -n "$1" ]; then
    echo "$1" >> "$NOTEFILE"
    echo "Added note: \"$(tail -n 1 "$NOTEFILE")\""
else
    if [[ "$BRAINDUMP_EDITOR" =~ vim ]]; then
        $BRAINDUMP_EDITOR + "$NOTEFILE"
    elif $BRAINDUMP_EDITOR_OPEN_WITH; then
        if [[ -f "$NOTEFILE" ]]; then
            LAST_LINE="`grep -c "" "$NOTEFILE" `"
        fi
        bd_open_file_line "$NOTEFILE" "$LAST_LINE"
    else
        $BRAINDUMP_EDITOR "$NOTEFILE"
    fi
fi
