#!/bin/bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

mkdir -p notes
CONTEXT_DESC=""
if [[ -x ".getdesc" ]]; then
    CONTEXT_DESC="_""`./.getdesc`"
elif [[ -f ".getdesc" ]]; then
    echo "Error: .getdesc exists but is not executable"
    exit 1
fi
DATE_DESC="_$(date +%Y-%m-%d)"
NOTEFILE="notes/note${CONTEXT_DESC}${DATE_DESC}.txt";


if [[ "$1" == "?" && -z "$2" ]]; then
    echo "$NOTEFILE"
elif [ -n "$1" ]; then
    echo "$1" >> "$NOTEFILE"
    echo "Added note: \"$(tail -n 1 "$NOTEFILE")\""
else
    vim + "$NOTEFILE"
fi
