#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

find ideas notes tasks -type f -not -regex ".*\.swp$" -not -regex ".*~$" -not -regex ".*#$" | xargs grep -irns "\[PIN\]" | less
