#!/bin/bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

find ideas notes tasks -type f | grep -vE ".*\.swp$" | grep -vE ".*~$" | xargs grep -irns "\[PIN\]" | less
