#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

if [ -z "`command -v qrencode`" ]; then
    echo "Error: qrencode not installed"
    exit;
fi

TOQR="$1"
if [[ -z "$TOQR" ]]; then
    TOQR="$(cat -)"
fi


PNG=/tmp/braindump_qr_"$RANDOM".png
qrencode "$TOQR" -o "$PNG"


if [ -n "`command -v xdg-open`" ]; then
    nohup xdg-open "$PNG" &> /dev/null & disown
else
    open "$PNG"
fi

echo "$TOQR"
