#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

COMPAT_SCRIPT=".scripts/editor_compat"
if [[ -f "$COMPAT_SCRIPT" ]];then
    source "$COMPAT_SCRIPT"
fi
if [[ -z "$BRAINDUMP_EDITOR" ]]; then
    BRAINDUMP_EDITOR="nano"
    function bd_open_file_line () { cat "/dev/null"; }
fi
export BRAINDUMP_EDITOR

if [[ -z "$BRAINDUMP_FILE_SUFFIX" ]]; then
    BRAINDUMP_FILE_SUFFIX=".txt"
fi

mkdir -p .braindump
QUEUEFILE=".braindump/queue${BRAINDUMP_FILE_SUFFIX}"

if [[ "$1" == "?" && -z "$2" ]]; then
    echo "$QUEUEFILE"
    exit
fi

if [ -n "$1" ]; then
    echo "$1" >> "$QUEUEFILE"
    echo "Added to queue: \"$(tail -n 1 "$QUEUEFILE")\""
else
    if [[ "$BRAINDUMP_EDITOR" =~ vim ]]; then
        $BRAINDUMP_EDITOR + "$QUEUEFILE"
    elif [[ "$BRAINDUMP_EDITOR_OPEN_WITH" == true ]]; then
        LAST_LINE="`grep -c "" "$QUEUEFILE" `"
        bd_open_file_line "$QUEUEFILE" "$LAST_LINE"
    else
        $BRAINDUMP_EDITOR "$QUEUEFILE"
    fi
fi
