#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

COMPAT_SCRIPT=".scripts/editor_compat"
if [[ -f "$COMPAT_SCRIPT" ]];then
    source "$COMPAT_SCRIPT"
fi
if [[ -z "$BRAINDUMP_EDITOR" ]]; then
    BRAINDUMP_EDITOR="nano"
    function bd_open_file_line () { cat "/dev/null"; }
fi
export BRAINDUMP_EDITOR

mkdir -p .braindump
SCRATCHFILE=".braindump/scratch.txt"
if [[ "$1" == "?" ]]; then
    echo "$SCRATCHFILE"
    exit
fi
$BRAINDUMP_EDITOR "$SCRATCHFILE"
