#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

mkdir -p .braindump
SCRATCHFILE=".braindump/scratch.txt"
if [[ "$1" == "?" ]]; then
    echo "$SCRATCHFILE"
    exit
fi
vim "$SCRATCHFILE";
