#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

COMPAT_SCRIPT=".scripts/editor_compat"
if [[ -f "$COMPAT_SCRIPT" ]];then
    source "$COMPAT_SCRIPT"
fi
if [[ -z "$BRAINDUMP_EDITOR" ]]; then
    BRAINDUMP_EDITOR="nano"
    function bd_open_file_line () { cat "/dev/null"; }
fi
export BRAINDUMP_EDITOR

if [[ -z "$1" ]]; then
    TASKNAME=""
elif [[ "$1" == "?" ]]; then
    TASKNAME=""
    QM="?"
else
    TASKNAME=$1
    shift
    if [[ "$1" == "?" ]]; then
        QM="?"
    fi
fi

if [[ -z "$BRAINDUMP_MAX_TASKS_SUGGESTED" ]]; then
    BRAINDUMP_MAX_TASKS_SUGGESTED=6
fi

CDIR="$(pwd)"
mkdir -p tasks
mkdir -p tasks/archived

if [[ -n "$TASKNAME" ]]; then
    cd tasks
    OLDIFS="$IFS"
    export IFS=$'\n'

    MATCHSTRING="$(find . -type f -iregex "^\\(.+\\|\\)$TASKNAME\\(.+\\|\\)$" -not -regex ".*\.swp$" -not -regex ".*~$" -not -regex ".*#$" -not -regex "^\\(.+\\|\\)archived\\(.+\\|\\)$")"
    for MATCH in $MATCHSTRING ; do
        MATCH_IDX=$(($MATCH_IDX + 1))
    done

    if [[ $MATCH_IDX -gt "$BRAINDUMP_MAX_TASKS_SUGGESTED" ]]; then
        # Suggest only BRAINDUMP_MAX_TASKS_SUGGESTED newest files
        MATCH_OLDER="$(($MATCH_IDX - $BRAINDUMP_MAX_TASKS_SUGGESTED))"
        if [[ $MATCH_OLDER -eq 1 ]]; then
            echo "Not suggesting $MATCH_OLDER less recently modified file"
        else
            echo "Not suggesting $MATCH_OLDER less recently modified files"
        fi
        select MATCHING in $(ls -c $MATCHSTRING | head -"$BRAINDUMP_MAX_TASKS_SUGGESTED" | sort); do break; done
    elif [[ $MATCH_IDX -gt 1 ]]; then
        select MATCHING in $(echo "$MATCHSTRING" | sort); do break; done
    else
        MATCHING="$MATCHSTRING"
    fi
    export IFS="$OLDIFS"
    cd "$CDIR"
fi


LOAD_SCRIPT=false
if [[ -z "$TASKNAME" ]]; then
    TASKFILE="tasks"
elif [ -z "$MATCHING" ]; then
    TASKFILE="tasks/${TASKNAME}_$(date +%Y-%m-%d).txt"
    LOAD_SCRIPT=true
elif [[ "$TASKNAME" == "todo" ]]; then
    TASKFILE="tasks/todo.txt"
else
    TASKFILE="tasks/${MATCHING[0]}"
    LOAD_SCRIPT=true
fi;

if [[ "$QM" == "?" ]]; then
    echo "$TASKFILE"
elif "$LOAD_SCRIPT"; then
    if [[ "$BRAINDUMP_EDITOR" =~ vim ]]; then
        $BRAINDUMP_EDITOR "$TASKFILE" -s .scripts/vim_task_start || $BRAINDUMP_EDITOR "$TASKFILE"
    elif [[ "$BRAINDUMP_EDITOR_OPEN_WITH" == true ]]; then
        TASK_LINE="`grep -n [START] "$TASKFILE" | sed "s/:.*//" | head -1`"
        bd_open_file_line "$TASKFILE" "$TASK_LINE"
    else
        $BRAINDUMP_EDITOR "$TASKFILE"
    fi
else
    $BRAINDUMP_EDITOR "$TASKFILE"
fi

cd $CDIR
