#!/bin/bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

mkdir -p tasks;

if [[ -z "$1" ]]; then
    TASKNAME=""
elif [[ "$1" == "?" ]]; then
    TASKNAME=""
    QM="?"
else
    TASKNAME=$1
    shift
    if [[ "$1" == "?" ]]; then
        QM="?"
    fi
fi

CDIR="$(pwd)"
mkdir -p tasks
mkdir -p tasks/archived

if [[ -n "$TASKNAME" ]]; then
    cd tasks
    MATCHING="$(printf "$(find . | grep -is $TASKNAME | grep -vE "~$" | grep -vE "\.swp$" | grep -vs archived)")"
    cd "$CDIR"
fi


LOAD_SCRIPT=false
if [[ -z "$TASKNAME" ]]; then
    TASKFILE="tasks"
elif [ -z "$MATCHING" ]; then
    TASKFILE="tasks/${TASKNAME}_$(date +%Y-%m-%d).txt"
    LOAD_SCRIPT=true
elif [[ "$TASKNAME" == "todo" ]]; then
    TASKFILE="tasks/todo.txt"
else
    TASKFILE="tasks/${MATCHING[0]}"
    LOAD_SCRIPT=true
fi;

if [[ "$QM" == "?" ]]; then
    echo "$TASKFILE"
elif "$LOAD_SCRIPT"; then
    vim "$TASKFILE" -s .scripts/vim_task_start
else
    vim "$TASKFILE"
fi

cd $CDIR
