#!/usr/bin/env bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

COMPAT_SCRIPT=".scripts/editor_compat"
if [[ -f "$COMPAT_SCRIPT" ]];then
    source "$COMPAT_SCRIPT"
fi
if [[ -z "$BRAINDUMP_EDITOR" ]]; then
    BRAINDUMP_EDITOR="nano -T 4 -Eli --softwrap"
fi
export BRAINDUMP_EDITOR

mkdir -p tasks

TODOFILE="tasks/todo.txt"

if [[ "$1" == "?" && -z "$2" ]]; then
    echo "$TODOFILE"
elif [ -n "$1" ]; then
    if [[ ! -f "$TODOFILE" ]]; then
        touch "$TODOFILE"
    fi
    NEWTODOS="`echo "$1" | cat - "$TODOFILE"`"
    echo "$NEWTODOS" > $TODOFILE &&
        echo "Added TODO: \"$(head -n 1 "$TODOFILE")\""
else
    $BRAINDUMP_EDITOR "$TODOFILE";
fi
