#!/bin/bash
# braindump
# (c) abstractsun
# License: GPL version 3 or, at your option, any later version

mkdir -p tasks

TODOFILE="tasks/todo.txt"

if [[ "$1" == "?" && -z "$2" ]]; then
    echo "$TODOFILE"
elif [ -n "$1" ]; then
    export RND=$RANDOM &&
    touch "$TODOFILE" &&
    echo "$1" | cat - "$TODOFILE" > /tmp/braindump_todo_"$RND".txt &&
    mv /tmp/braindump_todo_"$RND".txt "$TODOFILE" &&
    echo "Added TODO: \"$(cat "$TODOFILE" | grep . -m 1)\""
else
    vim "$TODOFILE";
fi
